gameid = voxsoul
backend = sqlite3
creative_mode = false
enable_damage = true
fixed_map_seed =
player_backend = files
auth_backend = files
mg_name = flat
mg_flags = caves, dungeons, light, decorations, biomes
mgflat_spflags = nolakes, nohouses
mgflat_np_depth = -10
mgflat_np_height = 0
