minetest.register_on_mods_loaded(function()
    assert(voxsoul.core, "voxsoul.core must exist")
    assert(voxsoul.core.is_digging_disabled == true, "digging should be disabled")
    minetest.log("action", "[voxsoul_tests] core tests passed")
end)

minetest.register_on_mods_loaded(function()
    assert(voxsoul.camera, "voxsoul.camera must exist")
    assert(type(voxsoul.camera.apply) == "function")
    minetest.log("action", "[voxsoul_tests] camera tests passed")
end)
