minetest.register_on_mods_loaded(function()
    assert(voxsoul.core, "voxsoul.core must exist")
    assert(voxsoul.core.is_digging_disabled == true, "digging should be disabled")
    minetest.log("action", "[voxsoul_tests] core tests passed")
end)

minetest.register_on_mods_loaded(function()
    assert(voxsoul.camera, "voxsoul.camera must exist")
    assert(type(voxsoul.camera.apply) == "function")
    minetest.log("action", "[voxsoul_tests] camera tests passed")
end)

minetest.register_on_mods_loaded(function()
    assert(voxsoul.entity and voxsoul.entity.hitbox, "voxsoul.entity.hitbox must exist")
    assert(voxsoul.combat and voxsoul.combat.stamina, "voxsoul.combat must exist")
    assert(voxsoul.player and voxsoul.player.stats, "voxsoul.player must exist")
    assert(voxsoul.player_model and voxsoul.player_model.registered_models["voxsoul_tarnished.b3d"], "player model must be registered")
    assert(voxsoul.boss and voxsoul.boss.registry.tree_sentinel, "boss registry must exist")
    minetest.log("action", "[voxsoul_tests] integration smoke passed")
end)
